# Generated by Django 4.1 on 2022-08-19 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_events_about_events_address_events_attachment_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='events',
            name='likes',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='events',
            name='view_count',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
