# Generated by Django 4.1 on 2022-08-19 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_events_likes_events_view_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='events',
            name='created_by',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='events',
            name='google_map',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='events',
            name='publish',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
