# Generated by Django 4.1 on 2022-08-20 04:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_remove_events_attachment_remove_events_event_price_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='events',
            name='featured_img',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
