# Generated by Django 4.0 on 2022-08-21 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0009_alter_events_featured_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='events',
            name='gallery',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
