# Generated by Django 4.0 on 2022-08-21 17:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0010_events_gallery'),
    ]

    operations = [
        migrations.RenameField(
            model_name='events',
            old_name='gallery',
            new_name='attachment',
        ),
    ]
