# Generated by Django 4.1 on 2022-08-22 07:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0012_events_gallery'),
    ]

    operations = [
        migrations.RenameField(
            model_name='events',
            old_name='gallery',
            new_name='images',
        ),
    ]
