# Generated by Django 4.1 on 2022-08-23 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0013_rename_gallery_events_images'),
    ]

    operations = [
        migrations.AlterField(
            model_name='events',
            name='images',
            field=models.ImageField(blank=True, max_length=200, null=True, upload_to='images'),
        ),
    ]
