# Generated by Django 4.1 on 2022-08-23 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0014_alter_events_images'),
    ]

    operations = [
        migrations.AlterField(
            model_name='events',
            name='event_end_time',
            field=models.TimeField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='events',
            name='event_start_time',
            field=models.TimeField(blank=True, max_length=10, null=True),
        ),
    ]
